In [1]:
import pandas as pd
import numpy as np

In [10]:
train_data = pd.read_csv("../rhea-soil-nutrient-prediction-challenge/Train.csv")
train_data.head()

,ID,Longitude,Latitude,start_date,end_date,horizon_lower,horizon_upper,Depth_cm,Al,B,...,Fe,Mg,Mn,N,ph,P,K,Na,S,Zn
0,O2TONM,35.18756,-8.62390,01/01/2008,31/12/2018,50,20,20-50,1109.856,NaN,...,92.366,200.601,107.257,2.24,5.942,NaN,283.103,NaN,NaN,NaN
1,BQLUK6,35.18558,-8.62300,01/01/2008,31/12/2018,50,20,20-50,1168.364,NaN,...,115.923,197.771,90.005,1.57,5.722,NaN,215.459,NaN,NaN,NaN
2,LSET8M,35.18579,-8.62221,01/01/2008,31/12/2018,50,20,20-50,1137.113,NaN,...,78.709,188.114,120.433,1.02,5.510,NaN,398.656,NaN,NaN,NaN
3,LEEL7I,35.18266,-8.62177,01/01/2008,31/12/2018,50,20,20-50,1117.349,NaN,...,127.527,156.417,112.036,1.12,5.817,NaN,267.354,NaN,NaN,NaN
4,LDNGO2,35.12984,-8.62005,01/01/2008,31/12/2018,50,20,20-50,1219.203,NaN,...,77.542,114.809,57.906,1.19,4.980,NaN,229.682,NaN,NaN,NaN

In [21]:
features = pd.read_csv('../features/olek-features.csv')
features.head()

,ID,Country,Area,Cropland nitrogen per unit area,Cropland phosphorus per unit area,Cropland potassium per unit area
0,O2TONM,Tanzania,Tanzania,6.777309,-2.492418,-7.380091
1,BQLUK6,Tanzania,Tanzania,6.777309,-2.492418,-7.380091
2,LSET8M,Tanzania,Tanzania,6.777309,-2.492418,-7.380091
3,LEEL7I,Tanzania,Tanzania,6.777309,-2.492418,-7.380091
4,LDNGO2,Tanzania,Tanzania,6.777309,-2.492418,-7.380091

In [18]:
df = train_data.merge(features, on='ID')
target_cols = ['ph', 'electrical_conductivity', 'Al', 'B', 'Ca', 'C_organic', 'C_total', 'Cu', 'Fe', 'Mg', 'Mn', 'N', 'P', 'K', 'Na', 'S', 'Zn']
other_cols = [col for col in df.columns if col not in target_cols]
new_columns = other_cols + target_cols
df = df[new_columns]
df.head()

,ID,Longitude,Latitude,start_date,end_date,horizon_lower,horizon_upper,Depth_cm,Country,Area,...,Cu,Fe,Mg,Mn,N,P,K,Na,S,Zn
0,O2TONM,35.18756,-8.62390,01/01/2008,31/12/2018,50,20,20-50,Tanzania,Tanzania,...,2.259,92.366,200.601,107.257,2.24,NaN,283.103,NaN,NaN,NaN
1,BQLUK6,35.18558,-8.62300,01/01/2008,31/12/2018,50,20,20-50,Tanzania,Tanzania,...,1.822,115.923,197.771,90.005,1.57,NaN,215.459,NaN,NaN,NaN
2,LSET8M,35.18579,-8.62221,01/01/2008,31/12/2018,50,20,20-50,Tanzania,Tanzania,...,1.913,78.709,188.114,120.433,1.02,NaN,398.656,NaN,NaN,NaN
3,LEEL7I,35.18266,-8.62177,01/01/2008,31/12/2018,50,20,20-50,Tanzania,Tanzania,...,2.876,127.527,156.417,112.036,1.12,NaN,267.354,NaN,NaN,NaN
4,LDNGO2,35.12984,-8.62005,01/01/2008,31/12/2018,50,20,20-50,Tanzania,Tanzania,...,1.825,77.542,114.809,57.906,1.19,NaN,229.682,NaN,NaN,NaN

In [19]:
df.describe()

,Longitude,Latitude,horizon_lower,horizon_upper,Cropland nitrogen per unit area,Cropland phosphorus per unit area,Cropland potassium per unit area,ph,electrical_conductivity,Al,...,Cu,Fe,Mg,Mn,N,P,K,Na,S,Zn
count,44298.000000,44298.000000,44298.000000,44298.000000,44298.000000,44298.000000,44298.000000,44295.000000,1907.000000,44296.000000,...,44257.000000,44257.000000,44298.000000,44255.000000,44257.000000,1909.000000,44298.000000,1948.000000,1909.000000,1909.000000
mean,26.309738,-4.240967,33.693620,9.129080,8.267376,-1.877417,-7.644802,6.403019,0.672805,801.060612,...,2.251211,109.728559,361.352863,126.566337,0.976671,6.211509,245.906346,37.988410,7.815769,1.256639
std,14.677473,9.448850,14.943173,9.962115,9.312740,1.554672,4.596612,0.877780,0.235945,309.640122,...,1.448901,42.325512,351.230863,67.226066,0.762748,4.735166,228.633212,19.018239,3.714587,0.385711
min,-13.433100,-29.981300,20.000000,0.000000,-3.442173,-3.448673,-18.097209,2.270000,0.191790,21.800000,...,0.001000,14.247000,4.995000,0.023000,0.060000,0.898422,2.926050,0.564734,2.693880,0.410652
25%,22.038550,-8.901090,20.000000,0.000000,6.777309,-2.492418,-7.380091,5.855000,0.500042,583.172750,...,1.081000,82.572000,141.363250,77.042000,0.510000,3.373750,101.882000,26.413400,5.574310,0.975072
50%,33.613220,-5.365200,20.000000,0.000000,6.777309,-2.492418,-7.380091,6.260000,0.640321,741.023500,...,2.052000,102.285500,235.021000,119.002000,0.770000,4.956590,176.947500,33.400350,6.907660,1.227800
75%,35.258660,1.468005,50.000000,20.000000,6.777309,-1.973700,-7.380091,6.758500,0.803680,970.567750,...,3.149000,129.164000,445.131750,167.687000,1.170000,7.534660,308.561000,44.606950,8.918460,1.489760
max,48.763800,14.886790,50.000000,20.000000,56.498218,3.902236,7.334409,9.914000,2.068690,2514.834000,...,19.831000,497.900000,4485.197000,735.093000,14.590000,83.700000,3830.490000,232.143000,44.533500,2.771600

In [5]:
print('Area and Country are different in {} rows.'.format((df['Country'] != df['Area']).sum()))

Area and Country are different in 0 rows.

In [20]:
df = df.drop(columns=['horizon_lower', 'horizon_upper', 'Area'])
df.head()

,ID,Longitude,Latitude,start_date,end_date,Depth_cm,Country,Cropland nitrogen per unit area,Cropland phosphorus per unit area,Cropland potassium per unit area,...,Cu,Fe,Mg,Mn,N,P,K,Na,S,Zn
0,O2TONM,35.18756,-8.62390,01/01/2008,31/12/2018,20-50,Tanzania,6.777309,-2.492418,-7.380091,...,2.259,92.366,200.601,107.257,2.24,NaN,283.103,NaN,NaN,NaN
1,BQLUK6,35.18558,-8.62300,01/01/2008,31/12/2018,20-50,Tanzania,6.777309,-2.492418,-7.380091,...,1.822,115.923,197.771,90.005,1.57,NaN,215.459,NaN,NaN,NaN
2,LSET8M,35.18579,-8.62221,01/01/2008,31/12/2018,20-50,Tanzania,6.777309,-2.492418,-7.380091,...,1.913,78.709,188.114,120.433,1.02,NaN,398.656,NaN,NaN,NaN
3,LEEL7I,35.18266,-8.62177,01/01/2008,31/12/2018,20-50,Tanzania,6.777309,-2.492418,-7.380091,...,2.876,127.527,156.417,112.036,1.12,NaN,267.354,NaN,NaN,NaN
4,LDNGO2,35.12984,-8.62005,01/01/2008,31/12/2018,20-50,Tanzania,6.777309,-2.492418,-7.380091,...,1.825,77.542,114.809,57.906,1.19,NaN,229.682,NaN,NaN,NaN