In [1]:
import pandas as pd
import numpy as np

In [2]:
data_train = pd.read_csv("../rhea-soil-nutrient-prediction-challenge/Train.csv")
data_train.head()

,ID,Longitude,Latitude,start_date,end_date,horizon_lower,horizon_upper,Depth_cm,Al,B,...,Fe,Mg,Mn,N,ph,P,K,Na,S,Zn
0,O2TONM,35.18756,-8.62390,01/01/2008,31/12/2018,50,20,20-50,1109.856,NaN,...,92.366,200.601,107.257,2.24,5.942,NaN,283.103,NaN,NaN,NaN
1,BQLUK6,35.18558,-8.62300,01/01/2008,31/12/2018,50,20,20-50,1168.364,NaN,...,115.923,197.771,90.005,1.57,5.722,NaN,215.459,NaN,NaN,NaN
2,LSET8M,35.18579,-8.62221,01/01/2008,31/12/2018,50,20,20-50,1137.113,NaN,...,78.709,188.114,120.433,1.02,5.510,NaN,398.656,NaN,NaN,NaN
3,LEEL7I,35.18266,-8.62177,01/01/2008,31/12/2018,50,20,20-50,1117.349,NaN,...,127.527,156.417,112.036,1.12,5.817,NaN,267.354,NaN,NaN,NaN
4,LDNGO2,35.12984,-8.62005,01/01/2008,31/12/2018,50,20,20-50,1219.203,NaN,...,77.542,114.809,57.906,1.19,4.980,NaN,229.682,NaN,NaN,NaN

In [79]:
features = data_train.iloc[:, :8]
features.head()

,ID,Longitude,Latitude,start_date,end_date,horizon_lower,horizon_upper,Depth_cm
0,O2TONM,35.18756,-8.62390,01/01/2008,31/12/2018,50,20,20-50
1,BQLUK6,35.18558,-8.62300,01/01/2008,31/12/2018,50,20,20-50
2,LSET8M,35.18579,-8.62221,01/01/2008,31/12/2018,50,20,20-50
3,LEEL7I,35.18266,-8.62177,01/01/2008,31/12/2018,50,20,20-50
4,LDNGO2,35.12984,-8.62005,01/01/2008,31/12/2018,50,20,20-50

In [3]:
data_test = pd.read_csv("../rhea-soil-nutrient-prediction-challenge/TestSet.csv")
data_test.head()

,ID,Latitude,Longitude,Depth_cm,Target_Al,Target_B,Target_Ca,Target_Cu,Target_Fe,Target_K,Target_Mg,Target_Mn,Target_N,Target_Na,Target_P,Target_S,Target_Zn
0,8ZMJRO,-0.746,37.094,0-20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,DCC6DM,-0.785,37.178,0-20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,T50LK1,-0.629,37.126,0-20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,FNLYT0,-0.351,35.308,0-20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,FP5E12,-1.894,36.987,0-20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# FE

## Country names

In [80]:
import reverse_geocoder as rg
import pycountry

In [81]:
coordinates = list(zip(features["Latitude"], features["Longitude"]))
locations = rg.search(coordinates)
locations_df = pd.DataFrame(locations)
locations_df.head()

        lat       lon     name  admin1 admin2  cc
0  -8.73333  35.28333  Makungu  Iringa         TZ
1  -8.73333  35.28333  Makungu  Iringa         TZ
2  -8.73333  35.28333  Makungu  Iringa         TZ
3  -8.73333  35.28333  Makungu  Iringa         TZ
4  -8.73333  35.28333  Makungu  Iringa         TZ

In [73]:
def get_country_name(country_code):
    try:
        country = pycountry.countries.get(alpha_2=country_code)
        return country.name
    except:
        return "Unknown"

In [82]:
features["Country"] = locations_df["cc"].apply(get_country_name)
features.head()

,ID,Longitude,Latitude,start_date,end_date,horizon_lower,horizon_upper,Depth_cm,Country
0,O2TONM,35.18756,-8.62390,01/01/2008,31/12/2018,50,20,20-50,"Tanzania, United Republic of"
1,BQLUK6,35.18558,-8.62300,01/01/2008,31/12/2018,50,20,20-50,"Tanzania, United Republic of"
2,LSET8M,35.18579,-8.62221,01/01/2008,31/12/2018,50,20,20-50,"Tanzania, United Republic of"
3,LEEL7I,35.18266,-8.62177,01/01/2008,31/12/2018,50,20,20-50,"Tanzania, United Republic of"
4,LDNGO2,35.12984,-8.62005,01/01/2008,31/12/2018,50,20,20-50,"Tanzania, United Republic of"

In [83]:
features["Country"] = features["Country"].replace("Tanzania, United Republic of", "Tanzania")
features.head()

,ID,Longitude,Latitude,start_date,end_date,horizon_lower,horizon_upper,Depth_cm,Country
0,O2TONM,35.18756,-8.62390,01/01/2008,31/12/2018,50,20,20-50,Tanzania
1,BQLUK6,35.18558,-8.62300,01/01/2008,31/12/2018,50,20,20-50,Tanzania
2,LSET8M,35.18579,-8.62221,01/01/2008,31/12/2018,50,20,20-50,Tanzania
3,LEEL7I,35.18266,-8.62177,01/01/2008,31/12/2018,50,20,20-50,Tanzania
4,LDNGO2,35.12984,-8.62005,01/01/2008,31/12/2018,50,20,20-50,Tanzania

In [84]:
nutrients = pd.read_csv("../datasets/Environment_Cropland_nutrient_budget_E_Africa.csv")
nutrients.head()

,Area Code,Area Code (M49),Area,Item Code,Item,Element Code,Element,Unit,Y1961,Y1961F,...,Y2020N,Y2021,Y2021F,Y2021N,Y2022,Y2022F,Y2022N,Y2023,Y2023F,Y2023N
0,4,'012,Algeria,5087,Mineral fertilizers,7275,Cropland nitrogen,t,9000.0000,X,...,NaN,71800.0000,E,NaN,81800.0000,E,NaN,90100.0000,E,NaN
1,4,'012,Algeria,5087,Mineral fertilizers,7276,Cropland nitrogen per unit area,kg/ha,1.2737,E,...,NaN,8.4760,E,NaN,9.6016,E,NaN,10.5532,E,NaN
2,4,'012,Algeria,5087,Mineral fertilizers,7280,Cropland phosphorus,t,9790.3800,E,...,NaN,19639.6200,E,NaN,24171.8400,E,NaN,23622.4800,E,NaN
3,4,'012,Algeria,5087,Mineral fertilizers,7281,Cropland phosphorus per unit area,kg/ha,1.3856,E,...,NaN,2.3185,E,NaN,2.8373,E,NaN,2.7668,E,NaN
4,4,'012,Algeria,5087,Mineral fertilizers,7282,Cropland potassium,t,12242.5000,E,...,NaN,24734.0000,E,NaN,26352.5000,E,NaN,30295.0000,E,NaN

In [87]:
columns = ["Area", "Item", "Element", "Unit"]
years = ["Y" + str(year) for year in range(2008, 2018)]
columns.extend(years)
nutrients = nutrients[columns]
nutrients.head()

,Area,Item,Element,Unit,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017
0,Algeria,Mineral fertilizers,Cropland nitrogen,t,20051.0000,37100.0000,60100.0000,56300.0000,72600.0000,69800.0000,98150.0000,101550.0000,91750.0000,87900.0000
1,Algeria,Mineral fertilizers,Cropland nitrogen per unit area,kg/ha,2.3870,4.4172,7.1454,6.6857,8.6116,8.2748,11.6302,12.0001,10.8998,10.3614
2,Algeria,Mineral fertilizers,Cropland phosphorus,t,6721.8120,19149.1200,12870.7200,14322.6000,22563.0000,28566.7200,31490.1000,26016.1200,23387.0400,22582.6200
3,Algeria,Mineral fertilizers,Cropland phosphorus per unit area,kg/ha,0.8002,2.2799,1.5302,1.7008,2.6764,3.3866,3.7314,3.0743,2.7784,2.6620
4,Algeria,Mineral fertilizers,Cropland potassium,t,11980.6350,17513.0000,21248.0000,21165.0000,24900.0000,27846.5000,30585.5000,37059.5000,23198.5000,24277.5000

In [85]:
nutrients["Item"].unique()

<StringArray>
[   'Mineral fertilizers',         'Manure applied', 'Atmospheric deposition',
   'Crop harvest removal',   'Crop residue removal',    'Biological fixation',
                   'Seed',               'Leaching',         'Volatilisation',
                  'Input',                'Outputs',       'Nutrient balance']
Length: 12, dtype: str

In [86]:
nutrients.groupby("Item").count()

,Area Code,Area Code (M49),Area,Item Code,Element Code,Element,Unit,Y1961,Y1961F,Y1961N,...,Y2020N,Y2021,Y2021F,Y2021N,Y2022,Y2022F,Y2022N,Y2023,Y2023F,Y2023N
Item,,,,,,,,,,,,,,,,,,,,,
Atmospheric deposition,110,110,110,110,110,110,110,102,102,0,...,0,106,106,0,106,106,0,106,106,0
Biological fixation,104,104,104,104,104,104,104,96,96,0,...,0,100,100,0,100,100,0,100,100,0
Crop harvest removal,330,330,330,330,330,330,330,306,306,0,...,0,318,318,0,318,318,0,318,318,0
Crop residue removal,330,330,330,330,330,330,330,306,306,0,...,0,318,318,0,318,318,0,318,318,0
Input,330,330,330,330,330,330,330,306,306,0,...,0,318,318,0,318,318,0,318,318,0
Leaching,110,110,110,110,110,110,110,102,102,0,...,0,106,106,0,106,106,0,106,106,0
Manure applied,330,330,330,330,330,330,330,306,306,0,...,0,318,318,0,318,318,0,318,318,0
Mineral fertilizers,330,330,330,330,330,330,330,302,302,0,...,0,318,318,0,318,318,0,318,318,0
Nutrient balance,495,495,495,495,495,495,495,459,459,0,...,0,477,477,0,477,477,0,477,477,0
Outputs,330,330,330,330,330,330,330,306,306,0,...,0,318,318,0,318,318,0,318,318,0
Seed,330,330,330,330,330,330,330,306,306,0,...,0,318,318,0,318,318,0,318,318,0
Volatilisation,110,110,110,110,110,110,110,102,102,0,...,0,106,106,0,106,106,0,106,106,0