In [1]:
import pandas as pd
import numpy as np

In [2]:
data_train = pd.read_csv("../rhea-soil-nutrient-prediction-challenge/Train.csv")
data_train.head()

,ID,Longitude,Latitude,start_date,end_date,horizon_lower,horizon_upper,Depth_cm,Al,B,...,Fe,Mg,Mn,N,ph,P,K,Na,S,Zn
0,O2TONM,35.18756,-8.62390,01/01/2008,31/12/2018,50,20,20-50,1109.856,NaN,...,92.366,200.601,107.257,2.24,5.942,NaN,283.103,NaN,NaN,NaN
1,BQLUK6,35.18558,-8.62300,01/01/2008,31/12/2018,50,20,20-50,1168.364,NaN,...,115.923,197.771,90.005,1.57,5.722,NaN,215.459,NaN,NaN,NaN
2,LSET8M,35.18579,-8.62221,01/01/2008,31/12/2018,50,20,20-50,1137.113,NaN,...,78.709,188.114,120.433,1.02,5.510,NaN,398.656,NaN,NaN,NaN
3,LEEL7I,35.18266,-8.62177,01/01/2008,31/12/2018,50,20,20-50,1117.349,NaN,...,127.527,156.417,112.036,1.12,5.817,NaN,267.354,NaN,NaN,NaN
4,LDNGO2,35.12984,-8.62005,01/01/2008,31/12/2018,50,20,20-50,1219.203,NaN,...,77.542,114.809,57.906,1.19,4.980,NaN,229.682,NaN,NaN,NaN

In [79]:
features = data_train.iloc[:, :8]
features.head()

,ID,Longitude,Latitude,start_date,end_date,horizon_lower,horizon_upper,Depth_cm
0,O2TONM,35.18756,-8.62390,01/01/2008,31/12/2018,50,20,20-50
1,BQLUK6,35.18558,-8.62300,01/01/2008,31/12/2018,50,20,20-50
2,LSET8M,35.18579,-8.62221,01/01/2008,31/12/2018,50,20,20-50
3,LEEL7I,35.18266,-8.62177,01/01/2008,31/12/2018,50,20,20-50
4,LDNGO2,35.12984,-8.62005,01/01/2008,31/12/2018,50,20,20-50

In [3]:
data_test = pd.read_csv("../rhea-soil-nutrient-prediction-challenge/TestSet.csv")
data_test.head()

,ID,Latitude,Longitude,Depth_cm,Target_Al,Target_B,Target_Ca,Target_Cu,Target_Fe,Target_K,Target_Mg,Target_Mn,Target_N,Target_Na,Target_P,Target_S,Target_Zn
0,8ZMJRO,-0.746,37.094,0-20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,DCC6DM,-0.785,37.178,0-20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,T50LK1,-0.629,37.126,0-20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,FNLYT0,-0.351,35.308,0-20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,FP5E12,-1.894,36.987,0-20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# FE

## Country names

In [119]:
import reverse_geocoder as rg
import pycountry

In [120]:
coordinates = list(zip(features["Latitude"], features["Longitude"]))
locations = rg.search(coordinates)
locations_df = pd.DataFrame(locations)
locations_df.head()

        lat       lon     name  admin1 admin2  cc
0  -8.73333  35.28333  Makungu  Iringa         TZ
1  -8.73333  35.28333  Makungu  Iringa         TZ
2  -8.73333  35.28333  Makungu  Iringa         TZ
3  -8.73333  35.28333  Makungu  Iringa         TZ
4  -8.73333  35.28333  Makungu  Iringa         TZ

In [121]:
def get_country_name(country_code):
    try:
        country = pycountry.countries.get(alpha_2=country_code)
        return country.name
    except:
        return "Unknown"

In [122]:
features["Country"] = locations_df["cc"].apply(get_country_name)
features.head()

,ID,Longitude,Latitude,start_date,end_date,horizon_lower,horizon_upper,Depth_cm,Country
0,O2TONM,35.18756,-8.62390,01/01/2008,31/12/2018,50,20,20-50,"Tanzania, United Republic of"
1,BQLUK6,35.18558,-8.62300,01/01/2008,31/12/2018,50,20,20-50,"Tanzania, United Republic of"
2,LSET8M,35.18579,-8.62221,01/01/2008,31/12/2018,50,20,20-50,"Tanzania, United Republic of"
3,LEEL7I,35.18266,-8.62177,01/01/2008,31/12/2018,50,20,20-50,"Tanzania, United Republic of"
4,LDNGO2,35.12984,-8.62005,01/01/2008,31/12/2018,50,20,20-50,"Tanzania, United Republic of"

In [124]:
features["Country"] = features["Country"].replace("Tanzania, United Republic of", "Tanzania")
features.head()

,ID,Longitude,Latitude,start_date,end_date,horizon_lower,horizon_upper,Depth_cm,Country
0,O2TONM,35.18756,-8.62390,01/01/2008,31/12/2018,50,20,20-50,Tanzania
1,BQLUK6,35.18558,-8.62300,01/01/2008,31/12/2018,50,20,20-50,Tanzania
2,LSET8M,35.18579,-8.62221,01/01/2008,31/12/2018,50,20,20-50,Tanzania
3,LEEL7I,35.18266,-8.62177,01/01/2008,31/12/2018,50,20,20-50,Tanzania
4,LDNGO2,35.12984,-8.62005,01/01/2008,31/12/2018,50,20,20-50,Tanzania

## Nutrients by country

In [125]:
nutrients = pd.read_csv("../datasets/Environment_Cropland_nutrient_budget_E_Africa.csv")
nutrients.head()

,Area Code,Area Code (M49),Area,Item Code,Item,Element Code,Element,Unit,Y1961,Y1961F,...,Y2020N,Y2021,Y2021F,Y2021N,Y2022,Y2022F,Y2022N,Y2023,Y2023F,Y2023N
0,4,'012,Algeria,5087,Mineral fertilizers,7275,Cropland nitrogen,t,9000.0000,X,...,NaN,71800.0000,E,NaN,81800.0000,E,NaN,90100.0000,E,NaN
1,4,'012,Algeria,5087,Mineral fertilizers,7276,Cropland nitrogen per unit area,kg/ha,1.2737,E,...,NaN,8.4760,E,NaN,9.6016,E,NaN,10.5532,E,NaN
2,4,'012,Algeria,5087,Mineral fertilizers,7280,Cropland phosphorus,t,9790.3800,E,...,NaN,19639.6200,E,NaN,24171.8400,E,NaN,23622.4800,E,NaN
3,4,'012,Algeria,5087,Mineral fertilizers,7281,Cropland phosphorus per unit area,kg/ha,1.3856,E,...,NaN,2.3185,E,NaN,2.8373,E,NaN,2.7668,E,NaN
4,4,'012,Algeria,5087,Mineral fertilizers,7282,Cropland potassium,t,12242.5000,E,...,NaN,24734.0000,E,NaN,26352.5000,E,NaN,30295.0000,E,NaN

In [126]:
columns = ["Area", "Item", "Element", "Unit"]
years = ["Y" + str(year) for year in range(2008, 2019)]
columns.extend(years)
nutrients = nutrients[columns]
nutrients.head()

,Area,Item,Element,Unit,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018
0,Algeria,Mineral fertilizers,Cropland nitrogen,t,20051.0000,37100.0000,60100.0000,56300.0000,72600.0000,69800.0000,98150.0000,101550.0000,91750.0000,87900.0000,109600.0000
1,Algeria,Mineral fertilizers,Cropland nitrogen per unit area,kg/ha,2.3870,4.4172,7.1454,6.6857,8.6116,8.2748,11.6302,12.0001,10.8998,10.3614,12.8994
2,Algeria,Mineral fertilizers,Cropland phosphorus,t,6721.8120,19149.1200,12870.7200,14322.6000,22563.0000,28566.7200,31490.1000,26016.1200,23387.0400,22582.6200,25564.8600
3,Algeria,Mineral fertilizers,Cropland phosphorus per unit area,kg/ha,0.8002,2.2799,1.5302,1.7008,2.6764,3.3866,3.7314,3.0743,2.7784,2.6620,3.0089
4,Algeria,Mineral fertilizers,Cropland potassium,t,11980.6350,17513.0000,21248.0000,21165.0000,24900.0000,27846.5000,30585.5000,37059.5000,23198.5000,24277.5000,28718.0000

In [127]:
nutrients = nutrients[nutrients["Item"] == "Nutrient balance"]
nutrients.head()

,Area,Item,Element,Unit,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018
50,Algeria,Nutrient balance,Cropland nitrogen,t,39667.9061,-22450.4098,17644.5822,7555.0066,6919.5023,2153.3936,61887.3995,57804.6506,52046.9558,50167.8480,21249.8251
51,Algeria,Nutrient balance,Cropland nitrogen per unit area,kg/ha,4.7224,-2.6730,2.0978,0.8972,0.8208,0.2553,7.3333,6.8308,6.1831,5.9136,2.5010
52,Algeria,Nutrient balance,Cropland phosphorus,t,-2479.5653,-6439.8979,-8890.8782,-10702.7834,-4567.6425,-404.2307,8811.0021,792.8569,-1206.6284,-2074.9548,-10054.3113
53,Algeria,Nutrient balance,Cropland phosphorus per unit area,kg/ha,-0.2952,-0.7667,-1.0571,-1.2710,-0.5418,-0.0479,1.0441,0.0937,-0.1433,-0.2446,-1.1833
54,Algeria,Nutrient balance,Cropland potassium,t,-12635.5515,-33582.0078,-29597.7075,-35870.4380,-38529.6503,-42322.5519,-30118.4722,-26955.2135,-41074.6636,-40213.4938,-52090.7712

In [128]:
nutrients["Element"].unique()

<StringArray>
[                 'Cropland nitrogen',    'Cropland nitrogen per unit area',
                'Cropland phosphorus',  'Cropland phosphorus per unit area',
                 'Cropland potassium',   'Cropland potassium per unit area',
   'Cropland nitrogen use efficiency', 'Cropland phosphorus use efficiency',
  'Cropland potassium use efficiency']
Length: 9, dtype: str

In [129]:
nutrients = nutrients[nutrients["Element"].isin(["Cropland nitrogen per unit area", "Cropland phosphorus per unit area", "Cropland potassium per unit area"])]
nutrients["Y_AVG"] = nutrients[years].mean(axis=1)
nutrients.head()

,Area,Item,Element,Unit,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y_AVG
51,Algeria,Nutrient balance,Cropland nitrogen per unit area,kg/ha,4.7224,-2.6730,2.0978,0.8972,0.8208,0.2553,7.3333,6.8308,6.1831,5.9136,2.5010,3.171118
53,Algeria,Nutrient balance,Cropland phosphorus per unit area,kg/ha,-0.2952,-0.7667,-1.0571,-1.2710,-0.5418,-0.0479,1.0441,0.0937,-0.1433,-0.2446,-1.1833,-0.401191
55,Algeria,Nutrient balance,Cropland potassium per unit area,kg/ha,-1.5042,-3.9983,-3.5189,-4.2596,-4.5703,-5.0174,-3.5689,-3.1853,-4.8796,-4.7402,-6.1309,-4.124873
110,Angola,Nutrient balance,Cropland nitrogen per unit area,kg/ha,7.3848,5.6716,7.7542,6.8697,11.7029,7.5706,13.0471,12.5781,9.7398,10.5133,8.5875,9.219964
112,Angola,Nutrient balance,Cropland phosphorus per unit area,kg/ha,-0.0211,-0.4694,-0.0401,0.4879,1.0390,-0.1206,0.1325,-0.0444,-0.3453,0.1213,-0.5499,0.017264

In [130]:
melt = nutrients.melt(
    id_vars=['Area', 'Element'],
    value_vars = years,
    var_name = 'Year',
    value_name = 'Value'
)

summary = melt.groupby(['Area', 'Element'])['Value'].agg(['min', 'max', 'mean', 'std']).reset_index()
summary.head()

,Area,Element,min,max,mean,std
0,Algeria,Cropland nitrogen per unit area,-2.6730,7.3333,3.171118,3.235247
1,Algeria,Cropland phosphorus per unit area,-1.2710,1.0441,-0.401191,0.671767
2,Algeria,Cropland potassium per unit area,-6.1309,-1.5042,-4.124873,1.201191
3,Angola,Cropland nitrogen per unit area,5.6716,13.0471,9.219964,2.465427
4,Angola,Cropland phosphorus per unit area,-0.5499,1.0390,0.017264,0.448005

In [131]:
nutrients_pivot = summary.pivot(index='Area', columns = 'Element', values = 'mean').reset_index()
nutrients_pivot.head()

Element,Area,Cropland nitrogen per unit area,Cropland phosphorus per unit area,Cropland potassium per unit area
0,Algeria,3.171118,-0.401191,-4.124873
1,Angola,9.219964,0.017264,-9.459173
2,Benin,-2.263545,-3.255536,-10.501491
3,Botswana,56.498218,2.144745,7.334409
4,Burkina Faso,3.875845,-1.323236,-0.840218

In [134]:
nutrients_pivot["Area"] = nutrients_pivot["Area"].replace("United Republic of Tanzania", "Tanzania")
nutrients_pivot["Area"].unique()

<StringArray>
[                         'Algeria',                           'Angola',
                            'Benin',                         'Botswana',
                     'Burkina Faso',                          'Burundi',
                       'Cabo Verde',                         'Cameroon',
         'Central African Republic',                             'Chad',
                          'Comoros',                            'Congo',
                    'Côte d'Ivoire', 'Democratic Republic of the Congo',
                         'Djibouti',                            'Egypt',
                'Equatorial Guinea',                          'Eritrea',
                         'Eswatini',                         'Ethiopia',
                     'Ethiopia PDR',                            'Gabon',
                           'Gambia',                            'Ghana',
                           'Guinea',                    'Guinea-Bissau',
                            'Kenya',                          'Lesotho',
                          'Liberia',                            'Libya',
                       'Madagascar',                           'Malawi',
                             'Mali',                       'Mauritania',
                        'Mauritius',                          'Morocco',
                       'Mozambique',                          'Namibia',
                            'Niger',                          'Nigeria',
                           'Rwanda',            'Sao Tome and Principe',
                          'Senegal',                       'Seychelles',
                     'Sierra Leone',                     'South Africa',
                      'South Sudan',                            'Sudan',
                   'Sudan (former)',                             'Togo',
                          'Tunisia',                           'Uganda',
                         'Tanzania',                           'Zambia',
                         'Zimbabwe']
Length: 55, dtype: str

In [135]:
features_nut = features.merge(nutrients_pivot, left_on="Country", right_on="Area", how="left")
features_nut.head()

,ID,Longitude,Latitude,start_date,end_date,horizon_lower,horizon_upper,Depth_cm,Country,Area,Cropland nitrogen per unit area,Cropland phosphorus per unit area,Cropland potassium per unit area
0,O2TONM,35.18756,-8.62390,01/01/2008,31/12/2018,50,20,20-50,Tanzania,Tanzania,6.777309,-2.492418,-7.380091
1,BQLUK6,35.18558,-8.62300,01/01/2008,31/12/2018,50,20,20-50,Tanzania,Tanzania,6.777309,-2.492418,-7.380091
2,LSET8M,35.18579,-8.62221,01/01/2008,31/12/2018,50,20,20-50,Tanzania,Tanzania,6.777309,-2.492418,-7.380091
3,LEEL7I,35.18266,-8.62177,01/01/2008,31/12/2018,50,20,20-50,Tanzania,Tanzania,6.777309,-2.492418,-7.380091
4,LDNGO2,35.12984,-8.62005,01/01/2008,31/12/2018,50,20,20-50,Tanzania,Tanzania,6.777309,-2.492418,-7.380091

In [138]:
features_nut[["Cropland nitrogen per unit area", "Cropland phosphorus per unit area", "Cropland potassium per unit area"]].isna().sum()

Cropland nitrogen per unit area      0
Cropland phosphorus per unit area    0
Cropland potassium per unit area     0
dtype: int64